language: node_js
node_js:
  - "0.10"
env:
  global:
    - SAUCE_USERNAME: jinzw
    - SAUCE_ACCESS_KEY: ce82cb32-53d1-4beb-a908-24fc80298021
install:
  - cd static
  - npm install

script: node node_modules/intern/runner.js config=mathDrawer/tests/intern